name: flashcards
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.4
  firebase_auth: ^4.3.0
  firebase_core: ^2.7.1
  get_it: ^7.2.0
  rxdart: ^0.27.7
  swipe_cards: ^2.0.0+1
  uuid: ^3.0.7
  json_annotation: ^4.8.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
