// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARahXw1vTNcWXW9F8aUJ2ZPc5fE83oeDU',
    appId: '1:223347116582:web:16cb1ec3b7b3371d1ab4e7',
    messagingSenderId: '223347116582',
    projectId: 'flutter-flashcards-83556',
    authDomain: 'flutter-flashcards-83556.firebaseapp.com',
    storageBucket: 'flutter-flashcards-83556.appspot.com',
    measurementId: 'G-KMEVZZ8TGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOLf34NlPBaiAA79-I6U98vc8sdXboBNs',
    appId: '1:223347116582:android:94fb59dd5a3f409c1ab4e7',
    messagingSenderId: '223347116582',
    projectId: 'flutter-flashcards-83556',
    storageBucket: 'flutter-flashcards-83556.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkfRQMWB4-0GZhSqqabJgKF9Y8nExI8DU',
    appId: '1:223347116582:ios:4e2c4a097449ebbf1ab4e7',
    messagingSenderId: '223347116582',
    projectId: 'flutter-flashcards-83556',
    storageBucket: 'flutter-flashcards-83556.appspot.com',
    iosClientId: '223347116582-nd8sneqpg2eblm9j5kqhtosqglea02os.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkfRQMWB4-0GZhSqqabJgKF9Y8nExI8DU',
    appId: '1:223347116582:ios:4e2c4a097449ebbf1ab4e7',
    messagingSenderId: '223347116582',
    projectId: 'flutter-flashcards-83556',
    storageBucket: 'flutter-flashcards-83556.appspot.com',
    iosClientId: '223347116582-nd8sneqpg2eblm9j5kqhtosqglea02os.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcards',
  );
}
